[package]
name = "game_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false }
serde = { version = "1.0", features = ["derive"] }
bevy_renet = "0.0.12"